#!/bin/env python

import argparse
from apftoolslib import queuestatus


parser = argparse.ArgumentParser(description='Prints aggregated status info queue by queue')
parser.add_argument("-H", "--headers", help="Prints the header of each column", action="store_true")
args = parser.parse_args()


qs = queuestatus(args)
qs.run()
print qs.printable()

