#!/usr/bin/env python 

"""
Output a factory config file only outputs ACTIVE sites
"""

import logging
import sys
import time

from ConfigParser import SafeConfigParser
from optparse import OptionParser
from urllib import urlopen

try:
    import json as json
except ImportError, err:
    import simplejson as json




class agis(object):

    def __init__(self):
    
        self.parseinputs()
        self.setuplogging()
    
        self.outputfile = open(self.options.outputfilename, 'w')

        self.template = open(self.options.templateconf)
        self.defaultsection = self.template.read()


    def parseinputs(self):
    
        parser = OptionParser(usage='''%prog [OPTIONS]
            Output a factory queue configuration using ACTIVE sites from the
            specified cloud and activity type.
            ''')
    
        parser.add_option("--conf",
                          dest="templateconf",
                          action="store",
                          default=None,
                          type="string",
                          help="template config file")

        parser.add_option("--output",
                          dest="outputfilename",
                          action="store",
                          default="queues.conf-agis",
                          type="string",
                          help="output filename")

        parser.add_option("--vo",
                          dest="vo",
                          action="store",
                          default=None,
                          type="string",
                          help="VO name")
    
        parser.add_option("--cloud",
                          dest="cloud",
                          action="store",
                          default=None,
                          type="string",
                          help="name of cloud")
    
        parser.add_option("--resourcetype",
                          dest="resourcetype",
                          action="store",
                          default=None,
                          type="string",
                          help="AGIS resource_type")

        parser.add_option("--activity",
                          dest="activity",
                          default=None,
                          action="store",
                          type="choice",
                          choices=['analysis','production'],
                          help="activity filter ('analysis' [default] or 'production')")
    
        parser.add_option("--site",
                          dest="site",
                          action="store",
                          default=None,
                          type="string",
                          help="LCG sitename, AGIS site")
    
        parser.add_option("--pandaresource",
                          dest="pandaresource",
                          action="store",
                          default=None,
                          type="string",
                          help="AGIS panda_resource")

        parser.add_option("--gatekeeper",
                          dest="gatekeeper",
                          action="store",
                          default=None,
                          type="string",
                          help="AGIS ce_name (or maybe the ce_endpoint ??? )")
    
        parser.add_option("--quiet",
                          dest="loglevel",
                          default=logging.WARNING,
                          action="store_const",
                          const=logging.WARNING,
                          help="Set logging level to WARNING [default]")
    
        parser.add_option("--info",
                          dest="loglevel",
                          default=logging.WARNING,
                          action="store_const",
                          const=logging.INFO,
                          help="Set logging level to INFO [default WARNING]")
    
        (self.options, args) = parser.parse_args()
    

    def setuplogging(self):

        self.logger = logging.getLogger()

        self.logger.setLevel(self.options.loglevel)
        #self.logger.setLevel(logging.DEBUG)

        fmt = '%(asctime)s (UTC) [ %(levelname)s ] :  %(message)s'
        formatter = logging.Formatter(fmt, '%T')
        formatter.converter = time.gmtime  # to convert timestamps to UTC

        handler = logging.FileHandler('apf-agis-config.log')
        handler.setFormatter(formatter)
        self.logger.addHandler(handler)

        #msg = 'Cloud: %s' % self.options.cloud.upper()
        #self.logger.info(msg)
        #msg = 'Activity: %s' % self.options.activity
        #self.logger.info(msg)


    def downloadinfo(self):

        url = 'http://atlas-agis-api.cern.ch/request/pandaqueue/query/list/?json&preset=schedconf.all'
        if self.options.cloud.upper():
            url += '&cloud=%s' % self.options.cloud.upper()
        logging.info(url)
    
        handle = urlopen(url)
        self.d = json.load(handle, 'utf-8')
        handle.close()
    

    def __checkvalue(self, opt, agisvalue):
        """
        opt is the value provided by the user thru the command line
        agisvalue is the value in AGIS

        -- if opt is None, or "", which means the user does not care, return True
        -- if opt has a value, return True if matches the AGIS value
        """

        if not opt:
            return True
        
        if opt:
            if opt == agisvalue:
                return True
            else:
                return False    


    def generateconfig(self):

        print >> self.outputfile, "# auto-generated by: apf-agis-config  %s" % ' '.join(sys.argv[1:])
    
        print >> self.outputfile, self.defaultsection
        
        for key in sorted(self.d):
            try:

                if not self.__checkvalue(self.options.vo, self.d[key]['vo_name']):
                    self.logger.debug("VO does not match: %s, %s" %(self.options.vo, self.d[key]['vo_name']) )
                    continue

                if not self.__checkvalue(self.options.cloud, self.d[key]['cloud']):
                    self.logger.debug("CLOUD does not match: %s, %s" %(self.options.cloud, self.d[key]['cloud']) )
                    continue

                if not self.__checkvalue(self.options.resourcetype, self.d[key]['resource_type']):
                    self.logger.debug("RESOURCETYPE does not match: %s, %s" %(self.options.resourcetype, self.d[key]['resource_type']) )
                    continue

                if not self.__checkvalue(self.options.activity, self.d[key]['type']):
                    self.logger.debug("ACTIVITY does not match: %s, %s" %(self.options.activity, self.d[key]['type']) )
                    continue

                if not self.__checkvalue(self.options.site, self.d[key]['site']):
                    self.logger.debug("SITE does not match: %s, %s" %(self.options.site, self.d[key]['site']) )
                    continue

                if not self.__checkvalue(self.options.pandaresource, self.d[key]['panda_resource']):
                    self.logger.debug("PANDARESOURCE does not match: %s, %s" %(self.options.pandaresource, self.d[key]['panda_resource']) )
                    continue



                if self.d[key]['site_state'] == 'ACTIVE':  # ?? what should we do with this ??
    
                    wmsqueue = self.d[key]['panda_resource']
                    cetype = self.d[key]['type']
                    memory = self.d[key]['memory']
                    corecount = self.d[key]['corecount']
                    
                    for q in self.d[key]['queues']:

                        if not self.__checkvalue(self.options.gatekeeper, q['ce_endpoint']):
                            self.logger.debug("GATEKEEPER does not match: %s, %s" %(self.options.gatekeeper, q['ce_endpoint']) )
                            continue

                        if q['ce_state'] != 'ACTIVE':
                            self.logger.debug("CE not active: %s (%s)" % (q['ce_name'], q['ce_state']))
                            continue
                        gramqueue = None 
                        nordugridrsl = None 
                        submitplugin = None
                        submitpluginstring = None
                        gramqueue = None
                        gramversion = None
                        creamenv = None
                        creamattr = None
                
                        if q['ce_flavour'] == 'LCG-CE' or q['ce_flavour'] == 'GLOBUS':
                
                            gridresource = '%s/jobmanager-%s' %(q['ce_endpoint'], q['ce_jobmanager'])
                            if q['ce_version'] == 'GT2':
                                submitplugin = 'CondorGT2'
                                submitpluginstring = 'condorgt2'
                                gramversion = 'gram2'
                            if q['ce_version'] == 'GT5':
                                submitplugin = 'CondorGT5'
                                submitpluginstring = 'condorgt5'
                                gramversion = 'gram5'
                            if q['ce_queue_name']:
                                gramqueue = q['ce_queue_name']

                            print >> self.outputfile, 'globusrsl.%s.queue = %s' % (gramversion, gramqueue)
                
                        elif q['ce_flavour'] == 'CREAM-CE':
                            gridresource = '%s/ce-cream/services/CREAM2 %s %s' %(q['ce_endpoint'], q['ce_jobmanager'], q['ce_queue_name'])
                            submitplugin = 'CondorCREAM'
                            submitpluginstring = 'condorcream'
                            if corecount:
                                creamattr = 'CpuNumber = %d' % corecount

                            if wmsqueue == 'NIKHEF-ELPROD_LONG':
                                print >> self.outputfile, 'batchsubmit.condorcream.condor_attributes = %(hold)s,%(remove)s,cream_attributes = CERequirements = "other.GlueCEPolicyMaxCPUTime >= 2520"'

                            if creamattr:
                                print >> self.outputfile, 'creamattr = %s' % creamattr
                                print >> self.outputfile, 'batchsubmit.condorcream.condor_attributes = %(hold)s,%(remove)s,cream_attributes = %(creamattr)s'
                            else:
                                print >> self.outputfile, 'batchsubmit.condorcream.condor_attributes = %(hold)s,%(remove)s'

                            
                        elif q['ce_flavour'] == 'ARC-CE':
                            # ignore :port part
                            gridresource = q['ce_endpoint'].split(':')[0]
                            submitplugin = 'CondorNordugrid'
                            submitpluginstring = 'condornordugrid'
                            nordugridrsl = '(jobname = arc_pilot)'
                            rsladd = '(runtimeenvironment = APPS/HEP/ATLAS-SITE-LCG)(runtimeenvironment = ENV/PROXY)'
                            rsladd += '(jobname = arc_pilot)(memory = %d)' % memory
                            if corecount:
                                rsladd += '(count = %d)' % corecount

                            print >> self.outputfile, 'batchsubmit.condornordugrid.nordugridrsl = %s' % nordugridrsl
                            print >> self.outputfile, 'nordugridrsl.nordugridrsladd = %s' % rsladd
                            print >> self.outputfile, 'nordugridrsl.queue = %s' % q['ce_queue_name']
                            print >> self.outputfile, 'nordugridrsl.addenv.RUCIO_ACCOUNT = pilot'
                            print >> self.outputfile, 'nordugridrsl.addenv.APF_PYTHON26 = 1'

                        else:
                            self.logger.debug("Unknown ce_flavour (%s) for %s (%s)" % (q['ce_flavour'], q['ce_name'], q['ce_queue_id']) )
                            continue
                
                        print >> self.outputfile, ''  
                        print >> self.outputfile, '[%s-%s]' % (self.d[key]['nickname'], q['ce_queue_id'])
                        print >> self.outputfile, 'batchqueue = %s' % key
                        print >> self.outputfile, 'wmsqueue = %s' % wmsqueue
                        print >> self.outputfile, 'batchsubmitplugin = %s' % submitplugin
                        print >> self.outputfile, 'batchsubmit.%s.gridresource = %s' % (submitpluginstring, gridresource)

                        if cetype == 'analysis':
                            print >> self.outputfile, 'batchsubmit.%s.proxy = atlas-analysis' % submitpluginstring
                            print >> self.outputfile, 'executable.arguments = %(executable.defaultarguments)s -u user'
                        elif cetype == 'production':
                            print >> self.outputfile, 'batchsubmit.%s.proxy = atlas-production' % submitpluginstring
                            print >> self.outputfile, 'executable.arguments = %(executable.defaultarguments)s'
    
    
            except KeyError, e:
              self.logger.debug('Key error: %s' % e)
        
        self.outputfile.close()


def main():
    agisobj = agis()
    #agisobj.parseinputs()
    #agisobj.setuplogging()
    agisobj.downloadinfo()
    agisobj.generateconfig()

if __name__ == "__main__":
    sys.exit(main())
